name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.4"

      - name: Build Linux X86_64
        run: |
          mkdir -p ./dist
          go build -o ./dist/plugstep ./cmd/plugstep
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-linux-amd64
          path: ./dist/plugstep
